### PR TITLE
Adding Code to Visualize Example Images

### PR DESCRIPTION
**Pull request by gwaygenomics**
I add code that is modified from https://github.com/jr0th/segmentation/blob/master/visualization/CellArt.ipynb and using input from @MarziehHaghighi to visualize example cell painting images

greyscale_channel

color_merged

I will use these images in an updated Figure 1A.

## Updating Cell Colors

I also updated cell colors in this PR. This should have probably been a different PR. I will update cell line colors again after feedback from special topics (too similar to other palette could be somewhat confusing/misleading)

### CODE REVIEW

**Comment by shntnu** [comment]
Love it!

**Comment by shntnu** [comment]
The one issue with the logic (IIUC it correctly) is that it rescales each image, so that makes it hard to compare one image with another.

**Comment by gwaygenomics** [comment]
oh, i realized I should tag @jr0th - thanks for making your code public and reusable!

**Comment by jr0th** [comment]
Sure thing! What an honor!

**Comment by gwaygenomics** [comment]
The honor is mine!

I added jr0th/segmentation#7 where I strongly recommend that you add a license to this body of work 😄

**Pull request merged**
