### PR TITLE
Updating Repurposing Hub Shiny App

### PR DESCRIPTION
**Pull request by gwaygenomics**
There are pretty big changes: https://gregway.shinyapps.io/repurposing_cellhealth_shiny/

- Updated repurposing hub data pushed through updated models
- Adding UMAP as an option for scatter plot type
- Adding Compound Explorer tab

Comments welcome! @shntnu @AnneCarpenter

### CODE REVIEW

**Comment by shntnu** [comment]
Not critical but would be nice to be have a nice data frame display - maybe use thishttps://shiny.rstudio.com/reference/shiny/0.12.1/tableOutput.html [here](https://github.com/broadinstitute/cell-health/blob/7268b29b51e3032cb0aee170e1f6c09a8b296413/4.apply/repurposing_cellhealth_shiny/ui.R#L49-L53)?

**Comment by shntnu** [comment]
It may be useful to quickly filter down to compound-readout combinations have a "good" dose response curve. I haven't checked, but one way to do this is to get a goodness-of-fit for fitting a dose curve

**Comment by shntnu** [comment]
The left panel is not colored by dose

image

**Comment by shntnu** [comment]
image

Its a little confused why DMSO is show separately here

**Comment by shntnu** [comment]
> Its a little confused why DMSO is show separately here; why not have it together with the drug, or at least on the same scale?

Actually I take that back  - separate is good, but would be good to have on the same scale if possible

**Comment by shntnu** [comment]
Add a legend, or something, explaining the gray dots (I assume they are DMSO)

image

**Comment by shntnu** [comment]
@gwaygenomics this is great! 

Once you have incorporated feedback from @AnneCarpenter as well, you could do a short (1 min) screen recording showing how you'd use the interface to navigate. I suspect the biologists would find that helpful to get oriented.

**Comment by gwaygenomics** [comment]
@shntnu - I've addressed all of your comments/suggestions. I will go ahead and merge this iteration. 

We will address new suggestions after the update presentation this afternoon.

cc @AnneCarpenter

**Pull request merged**
